INSERT INTO STOCK (ID, STOCK, BUY_QUANTITY, BUY_PRICE, BUY_VALUE, PROFIT_LOSS, PURCHASE_DATE, CLOSED) VALUES (1, 'ABC', 200, 100, 20000, NULL, CURRENT_TIMESTAMP, 'N')
INSERT INTO STOCK (ID, STOCK, BUY_QUANTITY, BUY_PRICE, BUY_VALUE, PROFIT_LOSS, PURCHASE_DATE, CLOSED) VALUES (2, 'PQR', 100, 200, 20000, NULL, CURRENT_TIMESTAMP, 'N')
INSERT INTO STOCK (ID, STOCK, BUY_QUANTITY, BUY_PRICE, BUY_VALUE, PROFIT_LOSS, PURCHASE_DATE, CLOSED) VALUES (3, 'XYZ', 300, 300, 9000, NULL, CURRENT_TIMESTAMP, 'N')

--INSERT INTO STOCK_ORDER (ID, PORTFOLIO_ID, SELL_QUANTITY, SELL_PRICE, SELL_VALUE, SOLD_DATE) VALUES (1, 1, 100, 120, 12000, CURRENT_TIMESTAMP)
--INSERT INTO STOCK_ORDER (ID, PORTFOLIO_ID, SELL_QUANTITY, SELL_PRICE, SELL_VALUE, SOLD_DATE) VALUES (2, 1, 50, 130, 6500, CURRENT_TIMESTAMP)
--INSERT INTO STOCK_ORDER (ID, PORTFOLIO_ID, SELL_QUANTITY, SELL_PRICE, SELL_VALUE, SOLD_DATE) VALUES (3, 1, 50, 140, 7000, CURRENT_TIMESTAMP)
